### ISSUE TITLE
incomplete biorxiv article?

### ISSUE THREAD

**Issue by nick-youngblut** [GitEnricoNeko/SRAHunter#2]
It appears that the [srahunter biorxiv article](https://www.biorxiv.org/content/10.1101/2024.03.19.585745v1.abstract) is incomplete. For example, there are conclusions section or a url to this GitHub repo. The article just abruptly ends with the `Comparison with existing tools` section. Maybe there was an issue with uploading the article to biorxiv?

**Comment by GitEnricoNeko** [comment]
Thank you for noticing that! 
Indeed there was an issue in the uploading of the paper to bioRxiv. 
From today on bioRxiv you can find an updated and complete version of the paper. 
[srahunter bioRxiv](https://www.biorxiv.org/content/10.1101/2024.03.19.585745v2
)
